java_library(
    name = "calibrationio",
    srcs = [
        "CalibrationDataLocation.java",
        "CalibrationLoader.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//:com_google_guava_guava",
        "//:com_google_inject_guice",
        "//:org_slf4j_slf4j_api",
        "//src/main/proto:calibration",
    ],
)
