package(default_visibility = ["//visibility:public"])

java_library(
    name = "timestamputils",
    srcs = [
        "TimestampUtils.java",
    ],
    deps = [
        "//:com_google_protobuf_protobuf_java",
    ],
)
