package(default_visibility = ["//visibility:public"])

java_library(
    name = "timestamputils",
    srcs = [
        "TimestampUtils.java",
    ],
    deps = [
        "//thirdparty/protobuf/google/protobuf:well_known_types",
    ],
)
