java_library(
    name = "messagewriter",
    srcs = [
        "MessageWriter.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//:com_google_guava_guava",
        "//:com_google_protobuf_protobuf_java",
        "//:org_slf4j_slf4j_api",
    ],
)
