java_library(
    name = "CameraGraphTest",
    srcs = [
        "CameraGraphTest.java",
    ],
    deps = [
        "//:junit_junit",
        "//:org_hamcrest_hamcrest_junit",
        "//:org_slf4j_slf4j_log4j12",
        "//src/main/java/edu/bu/vip/multikinect/controller/realtime:cameragraph",
        "//src/main/proto:calibration",
    ],
)
