java_library(
    name = "ratpackdevhandler",
    srcs = [
        "webconsole/DevRedirectHandler.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//:io_ratpack_ratpack_guice",
    ],
)
