package(default_visibility = ["//visibility:public"])

filegroup(
    name = "kinectdata",
    srcs = [
        "kinect1.dat",
        "kinect2.dat",
        "kinect_24_a.dat",
        "kinect_24_b.dat",
    ],
)

filegroup(
    name = "calibration",
    srcs = glob(["calibration/**"]),
)
