java_test(
    name = "fragmenter",
    srcs = [
        "FragmenterTest.java",
    ],
    resources = [
        "//src/test/resources:kinectdata",
    ],
    deps = [
        "//:junit_junit",
        "//src/main/java/edu/bu/vip/kinect/controllerv2/calibration:fragmenter",
        "//src/main/java/edu/bu/vip/kinect/controllerv2/calibration:inmemorycalibrationdatadb",
        "//src/main/proto:frame",
    ],
)
