// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/camera.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bu.Vip.Multikinect.Camera {

  /// <summary>Holder for reflection information generated from src/main/proto/camera.proto</summary>
  public static partial class CameraReflection {

    #region Descriptor
    /// <summary>File descriptor for src/main/proto/camera.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CameraReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtzcmMvbWFpbi9wcm90by9jYW1lcmEucHJvdG8SGWJ1LnZpcC5tdWx0aWtp",
            "bmVjdC5jYW1lcmEaGnNyYy9tYWluL3Byb3RvL2ZyYW1lLnByb3RvIg8KDVJl",
            "Y29yZE9wdGlvbnMyXQoGQ2FtZXJhElMKBnJlY29yZBIoLmJ1LnZpcC5tdWx0",
            "aWtpbmVjdC5jYW1lcmEuUmVjb3JkT3B0aW9ucxoZLmJ1LnZpcC5tdWx0aWtp",
            "bmVjdC5GcmFtZSIAKAEwAUIlCh1lZHUuYnUudmlwLm11bHRpa2luZWN0LmNh",
            "bWVyYUIER3JwY2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Bu.Vip.Multikinect.FrameReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bu.Vip.Multikinect.Camera.RecordOptions), global::Bu.Vip.Multikinect.Camera.RecordOptions.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RecordOptions : pb::IMessage<RecordOptions> {
    private static readonly pb::MessageParser<RecordOptions> _parser = new pb::MessageParser<RecordOptions>(() => new RecordOptions());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RecordOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bu.Vip.Multikinect.Camera.CameraReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecordOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecordOptions(RecordOptions other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecordOptions Clone() {
      return new RecordOptions(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RecordOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RecordOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RecordOptions other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
