package(
    default_visibility = ["//src/test:__subpackages__"],
)

java_library(
    name = "matchers",
    srcs = [
        "Matchers.java",
    ],
    deps = [
        "//:org_hamcrest_hamcrest_junit",
    ],
)
